dependencies:
  - python=3.9
  - pip
  - pip:
      - torch==2.0.0
      - torchvision==0.15.1
      - streamlit==1.26.0
      - numpy==1.25.0
      - pillow==10.0.0
      - matplotlib==3.8.0
      - plotly==5.17.0
      - albumentations==1.3.0
      - albumentations.pytorch==0.1.0
      - tqdm==4.66.1
      - regex==2024.12.1
